version: '3'
services:
  # Nginx service
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - laravel-network

  # PHP service
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - "9000:9000" # Map host machine's port 9000 to PHP-FPM's port 9000
    depends_on:
      - mysql
    networks:
      - laravel-network

  # MySQL service
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql # Persist MySQL data
    ports:
      - "3306:3306" # Map host machine's port 3306 to MySQL's port 3306
    networks:
      - laravel-network

  # Certbot service
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email mikel$


volumes:
  dbdata:

networks:
  laravel-network:
    driver: bridge